### ISSUE TITLE
JQF-Zest problems

### ISSUE THREAD

**Issue by pinkhat-m** [rohanpadhye/JQF#135]
Hello,

I am so interested to work with JQF-Zest.

I am trying to run a test for java application, but this java application is using [vert.x](https://vertx.io/). I would like to know whether JQF could support it or not?(because I encountered an error:"Exception in thread "vert.x-eventloop-thread-0" java.lang.IllegalStateException: class edu.berkeley.cs.jqf.fuzz.ei.ZestGuidance only supports single-threaded apps at the moment")

Is there any solution for this error?

Another question is that, if I have different unit test files which are using each other classes, how JQF is going to work when we are just passing one class and one method name to the command-line?

Thank you in advance for your time.

**Comment by rohanpadhye** [comment]
Thanks for your interest! I've pushed a change that re-enables fuzzing multi-threaded applications, though I haven't experimented with them yet. Could you try with the latest version? I am assuming you are using the Maven plugin to run fuzzing, so... you'll have to clone the JQF repo, run `mvn install`, and then from your test application add a dependency on `jqf-fuzz` version `1.8-SNAPSHOT` so that you are using the latest SNAPSHOT that you installed locally.

Let me know if fuzzing with latest snapshot version removes the error and works as expected without any other error.

For your second comment:
> if I have different unit test files which are using each other classes, how JQF is going to work when we are just passing one class and one method name to the command-line?

I am not really sure what you mean by "unit test files which are using each other classes". The class/method you pass into Zest is simply an entry point, just like a main method is an entry point to a Java application. Internally, the test method can invoke whatever it wants and use other classes as well. If you have multiple test methods annotated with `@Fuzz`, then you will have to fuzz them independently by running a separate `mvn jqf:fuzz` command for each entry point. Does that answer your question? Let me know if you meant something else.

**Comment by pinkhat-m** [comment]
Thank you so much for your answer.

Thank you for changes to support the multi-thread app but you mentioned before in "[JQF Maven Plugin](https://github.com/rohanpadhye/JQF/wiki/JQF-Maven-Plugin)" that if we use Maven plugin, no need to clone the repository. I am a bit confusing now.

For the second comment, what I meant is that, I have a unit test which is using the JQF annotation, so I am calling exactly the class and method for this test in the command-line, but the problem is that in this unit test, I have a function which is calling a function for another class which is a unit test by itself(both unit tests have their own junit anotations such as before, afterclass, etc ...), and what I saw is that JQF could not recognize the second (unit test)class. Is that clear now?

**Comment by pinkhat-m** [comment]
I should inform that the thread problem is fixed now, and I have my correct output.
Thank you for the changes.

Just to clarify the situation, I have two different tests:
The first one which I could get the output of fuzzing test(after thread changes that you have done) is the one that I have it as a simple junit test, it just directly goes to the application. so it works properly.
The second junit test that I have it, is the one that I explained before, which is using a function of another junit test (in another directory). It even cannot recognize the jqf: (Failed to execute goal edu.berkeley.cs.jqf:jqf-maven-plugin:1.8-SNAPSHOT:fuzz)

**Comment by pinkhat-m** [comment]
I have a new news!
I am running jqf for the simple unit test as I explained. Even for this one after a while I am getting same error like : [ERROR] Failed to execute goal edu.berkeley.cs.jqf:jqf-maven-plugin:1.8-SNAPSHOT:fuzz 

I am not sure this is related to our side or jqf?! is it related to the input?! could be related to the logic of our application?!

**Comment by rohanpadhye** [comment]
Thanks for the updates! Let me address both your comments:

> Thank you for changes to support the multi-thread app but you mentioned before in "JQF Maven Plugin" that if we use Maven plugin, no need to clone the repository. I am a bit confusing now.

Yes, in general you don't need to clone JQF to use the released version of the Maven plugin (e.g. version 1.7). However, I pushed a fix for your bug report and that's still unreleased. So, you need to clone and use a local SNAPSHOT version if you want to use the in-development `master` branch of JQF. Once I get confirmation that fixes work as expected,  I periodically make public releases. So, this fix will go into the public JQF 1.8 once I release it, and then you can use it directly without having to clone the repo. You can search for the public releases [here](https://search.maven.org/artifact/edu.berkeley.cs.jqf/jqf-maven-plugin).

>  I have a unit test which is using the JQF annotation, so I am calling exactly the class and method for this test in the command-line for fuzzing test, but the problem is that in this unit test, I have a function which is calling a function for another class which is a unit test by itself(both unit tests have their own junit anotations such as before, afterclass, etc ...), and what I saw is that JQF could not recognize the second (unit test)class.

Annotations on other methods shouldn't matter. The annotations are only checked on the entry point. After that, it's all a Java program. So, if you can run the same test using `mvn test`, then you should also be able to run the same test using `mvn jqf:fuzz`. 

> Even for this one after a while I am getting same error like : [ERROR] Failed to execute goal edu.berkeley.cs.jqf:jqf-maven-plugin:1.8-SNAPSHOT:fuzz

This just indicates that some exception was thrown but not what the issue was. Can you run your `mvn` command using the `-e` option to print stacktraces and see if you can find a root cause (typically a chain of exception stacktraces)? If this is still not useful, try running `mvn` with the `-X` option. This is debug mode and will print a large amount of logging, but you might be able to scroll through it and see if some unexpected exceptions were thrown from other threads, etc. which caused the eventual failure.

**Comment by pinkhat-m** [comment]
Thank you for the information of the releases and the second part.

Here is the error that I am getting:


            ```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal edu.berkeley.cs.jqf:jqf-maven-plugin:1.8-SNAPSHOT:fuzz (default-cli) on project ...... : Fuzzing revealed errors. Use mvn jqf:repro to reproduce failing test case.
                at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
                at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
                at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
                at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
                at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
                at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
                at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
                at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
                at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
                at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
                at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
                at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
                at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
                at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke (Method.java:566)
                at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
                at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
                at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
                at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
            Caused by: org.apache.maven.plugin.MojoFailureException: Fuzzing revealed errors. Use mvn jqf:repro to reproduce failing test case.
                at edu.berkeley.cs.jqf.plugin.FuzzGoal.execute (FuzzGoal.java:357)
                at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
                at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
                at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
                at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
                at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
                at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
                at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
                at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
                at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
                at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
                at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
                at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
                at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
                at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
                at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke (Method.java:566)
                at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
                at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
                at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
                at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)

```

and these are the maven information:

          Apache Maven 3.6.3
          Maven home: /usr/share/maven
          Java version: 11.0.10, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
          Default locale: en_US, platform encoding: UTF-8
          OS name: "linux", version: "5.8.0-50-generic", arch: "amd64", family: "unix"

I have tested different ways to solve it but nothing worked!!

**Comment by pinkhat-m** [comment]
Thank you for the information of the releases and the second part.

Here is the error that I am getting:

`org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal edu.berkeley.cs.jqf:jqf-maven-plugin:1.8-SNAPSHOT:fuzz (default-cli) on project ...... : Fuzzing revealed errors. Use mvn jqf:repro to reproduce failing test case.
                at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
                at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
                at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
                at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
                at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
                at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
                at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
                at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
                at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
                at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
                at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
                at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
                at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
                at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke (Method.java:566)
                at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
                at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
                at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
                at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
            Caused by: org.apache.maven.plugin.MojoFailureException: Fuzzing revealed errors. Use mvn jqf:repro to reproduce failing test case.
                at edu.berkeley.cs.jqf.plugin.FuzzGoal.execute (FuzzGoal.java:357)
                at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
                at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
                at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
                at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
                at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
                at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
                at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
                at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
                at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
                at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
                at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
                at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
                at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
                at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
                at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke (Method.java:566)
                at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
                at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
                at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
                at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
 `

and these are the maven information:

          Apache Maven 3.6.3
          Maven home: /usr/share/maven
          Java version: 11.0.10, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
          Default locale: en_US, platform encoding: UTF-8
          OS name: "linux", version: "5.8.0-50-generic", arch: "amd64", family: "unix"

I have tested different ways to solve it but nothing worked!!

**Comment by rohanpadhye** [comment]
It looks like the error message simply says: 
> Fuzzing revealed errors. Use mvn jqf:repro to reproduce failing test case.

That means fuzzing terminated normally because there were uncaught exceptions from the test. Did you see the Zest fuzzing status screen for a while and was there a timeout which caused it stop? If so, then is not a bug. it's simply saying that the fuzzer found some failing test inputs. You can run `mvn jqf:repro` to repro the failures.  You will probably have failing test inputs such as `target/fuzz-results/CLASS_NAME/METHOD_NAME/failures/id_000000` and so on. See the [compiler fuzzing tutorial](https://github.com/rohanpadhye/JQF/wiki/Fuzzing-a-Compiler#step-5-fuzz-using-js-generator----more-coverage--new-bugs) for an example. Let me know if you don't see an exception when you run the repro tests.

**Comment by pinkhat-m** [comment]
I know what you are saying, for sure I have read all the information that you have put in the git repo.
Actually, I have put the timeout on 1 hour(60m), and the test is stopped randomly at different time before one hour. (I could see one or two or at most three failures)

Shouldn't be stopped exactly after one hour?

**Comment by pinkhat-m** [comment]
`E
Time: 71.716
There was 1 failure:
1) ....
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
	at edu.berkeley.cs.jqf.fuzz.util.Coverage.computeNewCoverage(Coverage.java:126)
	at edu.berkeley.cs.jqf.fuzz.ei.ZestGuidance.computeResponsibilities(ZestGuidance.java:767)
	at edu.berkeley.cs.jqf.fuzz.ei.ZestGuidance.handleResult(ZestGuidance.java:637)
	at edu.berkeley.cs.jqf.fuzz.junit.quickcheck.FuzzStatement.evaluate(FuzzStatement.java:185)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at edu.berkeley.cs.jqf.fuzz.junit.GuidedFuzzing.run(GuidedFuzzing.java:208)
	at edu.berkeley.cs.jqf.fuzz.junit.GuidedFuzzing.run(GuidedFuzzing.java:154)
	at edu.berkeley.cs.jqf.plugin.FuzzGoal.execute(FuzzGoal.java:347)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)

FAILURES!!!
Tests run: 1,  Failures: 1
`

I could get this log by using -X.
It didn't give me any failures and it stopped.

**Comment by pinkhat-m** [comment]
I have another question.

Most of the failures and corpus cannot be opened to see their contents, how we can know about the input which causes the failure?

**Comment by rohanpadhye** [comment]
> Shouldn't be stopped exactly after one hour?

Ideally, yes. Unless something went terribly wrong.... which it seems like it did:

> java.util.ConcurrentModificationException

Thanks for reporting this! It was what I suspected. This is why Zest did not support multi-threading earlier. From the stacktrace, it seems like while Zest was processing the result of one test input execution, something else from the application was concurrently executing code that updated coverage. Ideally, your application should not be running things between distinct test executions, otherwise it can lead to lots of non-determinism. If new threads are started during a test, then those threads should be joined before the test method returns. In this case, it seems that something is running concurrently while Zest is processing results of a test execution. Since you mentioned vertx earlier, I am assuming that vertx is running something in the background in between test executions.

I can try to push a fix that applies some synchronization to suppress this ConcurrentModificationException,  but the results of fuzzing may not be great if there's background stuff going on. Let me get back to you on this.

> Most of the failures and corpus cannot be opened to see their contents, how we can know about the input which causes the failure?

You basically run `mvn jqf:repro` with the input to reproduce the test execution. You can also provide a directory instead of a file and all the inputs in that dir will be repro'd. When doing this, you can use `-DprintArgs` f;ag  to print out the parameters to the test method (this is only useful if the parameters are objects that can be printed nicely using `toString()`). If you see an exception from your test, that means a test failure occurred. You can of course add print/logging statements or debug in your IDE (the `@Fuzz(repro="/path/to/file")` syntax is useful for quickly repro-stepthrough-debugging in an IDE).

**Comment by pinkhat-m** [comment]
Sure, thank you for your time. I look forward to hear from you.

**Comment by rohanpadhye** [comment]
I've pushed a fix in 38dda7a that should take prevent the ConcurrentModificationExceptions. If they do occur again, you should get less confusing error messages due to the change in 8c06d14.

Please try again with the latest version (`git pull` on the `master` branch, then `mvn install`, and then fuzz with the SNAPSHOT version as before). Let me know if the error goes away.

Note: While this fix might suppress the errors coming out of Zest, I want to reiterate that fuzzing results will be very unpredictable and sometimes non-reproducible if your test has not completed all its work before returning from the test method. For example, this kind of test is very bad:

```java
@Fuzz
public void test(int x) {
   Thread t = new Thread(someWorkFunc);
   t.start();
   // missing t.join()
}
```
In this example, all of the coverage achieved by `someWorkFunc` will not be collected by the time the test method returns, so it will non-deterministically spill over into the coverage for future test executions. To prevent this sort of weirdness, make sure that all background threads join before returning from the test method. If the threads are running in other libraries, e.g. vertx, then make sure that they are not doing input-dependent work (e.g. event handling) after your test method returns. I am assuming there whould be some sort of API to let you block the test method until those event handlers to complete.

Hope this helps.

**Comment by pinkhat-m** [comment]
Thank you for the changes, I think now it is fine and I don't see that error anymore. (but I am running more tests to make sure about it, and I will let you know if there is a problem)

Actually, I have another problem.
This application is a multi-module application, so in the case that I was explaining I have a test which is calling a function of another class, I should have said of another module. so now when I run the test in the submodule that I have my configuration of JQF, it cannot be run and I am getting below error which seems it is from your side:

`Fuzzing stopped due to guidance exception: java.lang.IllegalArgumentException: bound must be positive
edu.berkeley.cs.jqf.fuzz.guidance.GuidanceException: java.lang.IllegalArgumentException: bound must be positive
	at edu.berkeley.cs.jqf.fuzz.junit.quickcheck.FuzzStatement.evaluate(FuzzStatement.java:150)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at edu.berkeley.cs.jqf.fuzz.junit.GuidedFuzzing.run(GuidedFuzzing.java:208)
	at edu.berkeley.cs.jqf.fuzz.junit.GuidedFuzzing.run(GuidedFuzzing.java:154)
	at edu.berkeley.cs.jqf.plugin.FuzzGoal.execute(FuzzGoal.java:347)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at edu.berkeley.cs.jqf.fuzz.ei.ZestGuidance$LinearInput.fuzz(ZestGuidance.java:1154)
	at edu.berkeley.cs.jqf.fuzz.ei.ZestGuidance.lambda$getInput$0(ZestGuidance.java:597)
	at edu.berkeley.cs.jqf.fuzz.ei.ZestGuidance.conditionallySynchronize(ZestGuidance.java:937)
	at edu.berkeley.cs.jqf.fuzz.ei.ZestGuidance.getInput(ZestGuidance.java:556)
	at edu.berkeley.cs.jqf.fuzz.junit.quickcheck.FuzzStatement.evaluate(FuzzStatement.java:124)
	... 39 more
`

I would like to know whether this also has a solution or not?

**Comment by pinkhat-m** [comment]
> Thank you for the information of the releases and the second part.
> 
> Here is the error that I am getting:
> 
> `org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal edu.berkeley.cs.jqf:jqf-maven-plugin:1.8-SNAPSHOT:fuzz (default-cli) on project ...... : Fuzzing revealed errors. Use mvn jqf:repro to reproduce failing test case. at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215) at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156) at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148) at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117) at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81) at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56) at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128) at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305) at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192) at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105) at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957) at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289) at org.apache.maven.cli.MavenCli.main (MavenCli.java:193) at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method) at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62) at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke (Method.java:566) at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282) at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225) at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406) at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347) Caused by: org.apache.maven.plugin.MojoFailureException: Fuzzing revealed errors. Use mvn jqf:repro to reproduce failing test case. at edu.berkeley.cs.jqf.plugin.FuzzGoal.execute (FuzzGoal.java:357) at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137) at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210) at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156) at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148) at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117) at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81) at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56) at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128) at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305) at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192) at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105) at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957) at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289) at org.apache.maven.cli.MavenCli.main (MavenCli.java:193) at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method) at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62) at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke (Method.java:566) at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282) at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225) at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406) at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347) `
> 
> and these are the maven information:
> 
> ```
>       Apache Maven 3.6.3
>       Maven home: /usr/share/maven
>       Java version: 11.0.10, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
>       Default locale: en_US, platform encoding: UTF-8
>       OS name: "linux", version: "5.8.0-50-generic", arch: "amd64", family: "unix"
> ```
> 
> I have tested different ways to solve it but nothing worked!!


If I still see this log but after the timeout that I set, is it fine?

**Comment by rohanpadhye** [comment]
> If I still see this log but after the timeout that I set, is it fine?

Yes, the "Fuzzing revealed errors. Use mvn jqf:repro to reproduce failing test case." is just a message that the fuzz test had failures. This is similar to when you run `mvn test` and your test fails. The convention in Maven is that the test/fuzz goal is not successful unless all tests pass without exceptions.

Note to self: several people are confused by this, so maybe this should be allowed to terminate successfully even if fuzzing revealed errors.

> I would like to know whether this also has a solution or not?

Honestly, I cannot debug this without an example. For me, inter-module fuzzing works just fine as long as Maven has all the dependencies set up correctly. The general convention is that if `mvn test` can find the classes, then `mvn jqf:fuzz` will also find the same classes---in fact JQF uses Maven's test classpath itself.

If you are seeing these errors and would like to debug them, please create a minimal working example (e.g. see how [another issue was resolved with a minimal reproducible example](https://github.com/rohanpadhye/JQF/issues/65#issuecomment-784393649)).

**Comment by pinkhat-m** [comment]
> > I would like to know whether this also has a solution or not?
> 
> Honestly, I cannot debug this without an example. For me, inter-module fuzzing works just fine as long as Maven has all the dependencies set up correctly. The general convention is that if `mvn test` can find the classes, then `mvn jqf:fuzz` will also find the same classes---in fact JQF uses Maven's test classpath itself.
> 
> If you are seeing these errors and would like to debug them, please create a minimal working example (e.g. see how [another issue was resolved with a minimal reproducible example](https://github.com/rohanpadhye/JQF/issues/65#issuecomment-784393649)).

Yes, actually I do not have any problem for running the test by 'mvn test' while it is not possible by 'mvn jqf:fuzz'.
I will try to create a minimal working example if it is possible to make the same situation.

Thank you for your time.

**Comment by pinkhat-m** [comment]
Ok I have found the problem, but it is a bit weird to me!

I have found the same issue here: https://github.com/rohanpadhye/jqf/issues/42

Actually, I have kind of the same problem.
I had no parameter for the test method in test driver, because I was passing my input(just one input as a test) as a file inside the method, so JQF gave me that error.
Now I have just add one parameter with @From but I am not using this parameter inside my function; the weird part is that having it like this is enough to be able to run the test! no need to use parameter at all!

**Comment by rohanpadhye** [comment]
Ahh yes. That makes sense. You have to give JQF something to generate. With no parameter, there is no input to fuzz! 

If you have one input parameter but you are not using in your test method, then why do you need to run fuzzing? I don't understand how fuzzing is useful if you don't have an input. Isn't it simply equivalent to running `mvn test` many times?

**Comment by pinkhat-m** [comment]
Yes, it was my mistake.
I have two different test drivers and I just wrote one generator which is not compatible with the second test. So I could not use the generator and I thought I can just run the test no matter what would be the result!

**Comment by pinkhat-m** [comment]
Sure, thank you so much for your time.
